### ISSUE TITLE
zookeeper: connection refused

### ISSUE THREAD

**Issue by stelcheck** [Wizcorp/frontrunner#12]
```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

And yet the app keeps on running... we need to have some reconnect logic as well as bailout on failure.

**Comment by stelcheck** [comment]
Actually, got this wrong. this happens when marathon died...

**Comment by MiLk** [comment]
frontrunner is unable to refresh the proxy configuration if marathon is down, but it should continue to run as expected.

Except a better error message, what do you want to change?

**Comment by stelcheck** [comment]
Perhaps just connect retry?

**Comment by MiLk** [comment]
I wonder if this error doesn't come from https://github.com/Wizcorp/frontrunner/blob/29ee88146bf4e7db7700a5038f87696479b33e50/lib/marathon.js#L34.
The zookeeper module already has a retry mechanism.

Edit: Confirmed, it comes from the http request.

**Comment by stelcheck** [comment]
Is it possible to log-and-retry forever?

**Comment by MiLk** [comment]
#13 updated.
