### ISSUE TITLE
Have an option to use node-proxy internally instead of reconfiguring HAProxy

### ISSUE THREAD

**Issue by stelcheck** [Wizcorp/frontrunner#2]
It would be great if frontrunner had an option to be the load-balancer itself in the future. For smaller setup where performance is less critical or where HAProxy is not desirable, that could be a nice to have.

If there are enough people which show their interest here, I think it could be wise to integrate that feature into frontrunner

**Comment by ralph-tice** [comment]
In what circumstances would HAProxy not be desirable ?

**Comment by stelcheck** [comment]
I think it depends on:
1. What you are currently used to. If you prefer nGinx, for instance, it would be great if you could have the configurator do nGinx. I think @MiLk already has plans to support other load balancing software in the future
2. Simplicity. Some prefer less moving part. 

I am thinking of cases like Nodejitsu where they are writing their own LB in Node.js (unless my knowledge is antiquated?). Could be cool if frontrunner could 
1. Be the LB itself, out of the box. Simple, battery-included.
2. Be a node modules which you include and plug in into your own software (maybe as a connect middleware or something?)

For our use-case, actually, HAProxy is more than fine. I love it, it gets the job done. But I am guessing that broader support could be something others may find benefits in...

**Comment by MiLk** [comment]
I'm not sure that frontrunner being the LB is a good idea. In case of error/exception in the LB module, frontrunner will crash.

I prefer to keep applications small, but robust. Do one thing, but do it well.

But, I don't want to depend on HAProxy, so I will provide support at least for Nginx.
Support for [varnish](https://www.varnish-cache.org/) and a simple proxy based on [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) or [poise](https://github.com/jeffsu/poise) may be provided in the future.

I'd rather make a new proxy solution in node.js which requires frontrunner as a module, than embed a proxy in frontrunner.

**Comment by stelcheck** [comment]
Makes sense.
